### ISSUE TITLE
Install scenery on Aerofly FS 2 ?

### ISSUE THREAD

**Issue by crystalnoir** [nickhod/aeroscenery#4]
Hi, 
First of all congratulation for this awesome tool ! However, I can generate tiles, the software works without error. I have setup my folders (sdk tools, Aerofly FS 2 folder...), but after the process is finished how I can use them . I try to launch the simulator but when I'm on a tile I have generate there is no texture at all, just the simple dirt texture (basic texture). I am missing something ?

I searched for the generate files but I can't find nothing. Same in the Aeroscenery folder in the documents folder.

Thank you in advance, 

Regards, 

Guillaume

**Comment by Pummelchen** [comment]
Same problem, not sure how to proceed after geoconvert shows "100%". We need a simple step by step guidelines for ppl who just fly around and are not flight sim programmers.

**Comment by Pummelchen** [comment]
Look like in AeroScenery you need to:

- go back to the Map view, click on your tile, click the "Open Folder" button
- take the PNG files from "20-geoconvert-raw" folder
- take  TTC files from "20-geoconvert-ttc" folder (not sure if this step is required)
- copy those to: C:\Users\Administrator\Documents\Aerofly FS 2\scenery\images
Replace Administrator with your Windows Username

I would wish these steps to be automated, plus maybe a calculation of the total download size would be nice too :)

**Comment by nickhod** [comment]
Now done in 1.0.1
