### ISSUE TITLE
Issue with "Shrink TMC grid squares"

### ISSUE THREAD

**Issue by pmb2019** [nickhod/aeroscenery#7]
I try to set

"Shrink TMC grid squares by"

to the value of 0.01. However, the next time I enter "Settings" or restart Aeroscenery it is reset to 001.  Is there any way to modify this value? Uninstallung and reinstalling AeroScenery does not help. For detail, I refer to this thread:

[https://www.aerofly.com/community/forum/index.php?thread/14427-aeroscenery-made-scenery-loading-in-patches/&postID=78178#post78178](url)

This is the most recent version, i.e. 1.0.1.

Thanks for keeping an eye on this.

Kind regards, Michael

**Comment by nickhod** [comment]
Fixed in 1.1.0-beta
